### PR TITLE
Changing the tcp-ip communication protocol

### PR DESCRIPTION
**Pull request by Peter-Vincent**
Updates to the client and server code to allow for inter-process, -network and -language communication with Zapit.

### CODE REVIEW

**Comment by raacampbell** [comment]
What is the idea behind the first commit (the "different memory one")?

**Comment by raacampbell** [comment]
Also, did you switch the line endings from Unix to Windows in the first commit? All the lines are listed as changes, which makes it hard to see what has altered. I'll take a look more carefully soon.

**Comment by Peter-Vincent** [comment]
Messages to the server are different from messages received from the server, since the received messages contain a timestamp.  This means we can't default to reading the same number of bytes from the buffer, similarly the readDataFnc would need to be different and the structure of the buffer is also not shared.  The second commit extracts these components from the tcpip parent class and implements them directly into the client and server classes.  DIfferent memory should be memory layout - referring to the buffer struct interpreting the message in different ways depending on if its client or server.

**Comment by Peter-Vincent** [comment]
Oh damn, yes it looks like it did.  Sorry about that, do you know how I can undo that?

**Comment by raacampbell** [comment]
> Oh damn, yes it looks like it did. Sorry about that, do you know how I can undo that?

There is a bash script in the repo that fixes all files. Otherwise you just have change in your editor and re-save. Then push the changes. 

Git was randomly changing large numbers of files over and I stopped that with a config setting somwhere in the .git directory. I don't think that setting blocks you from manually changing the line endings, though.

**Pull request closed without merging**
